# Docket yaml configuration file specification

# Where the main `manifest.json` file is located for this repository
main: manifest.json

# maximum depth of dependencies to follow
depth: 10

# local of downloaded files
dest: ~/.docket/dependencies

# cache dependencies
cache: true

# time to live: amount of time to keep cached dependencies
tol: 1d

# downloader used for retrieving dependencies
# this may be an array and each preset will be run in the order specified
# dependencies with an absolute url always use the full url
preset: github
